/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChallengesByKeywordGraphResponse } from '../../models/challenges-by-keyword-graph-response';

export interface GetChallengesByKeywordGraphKeywordsChallengesGraphGet$Params {
  kw: string;
}

export function getChallengesByKeywordGraphKeywordsChallengesGraphGet(http: HttpClient, rootUrl: string, params: GetChallengesByKeywordGraphKeywordsChallengesGraphGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ChallengesByKeywordGraphResponse>> {
  const rb = new RequestBuilder(rootUrl, getChallengesByKeywordGraphKeywordsChallengesGraphGet.PATH, 'get');
  if (params) {
    rb.query('kw', params.kw, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChallengesByKeywordGraphResponse>;
    })
  );
}

getChallengesByKeywordGraphKeywordsChallengesGraphGet.PATH = '/keywords/challenges/graph';
