/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { KeywordListResponse } from '../../models/keyword-list-response';

export interface GetKeywordsListKeywordsListGet$Params {
}

export function getKeywordsListKeywordsListGet(http: HttpClient, rootUrl: string, params?: GetKeywordsListKeywordsListGet$Params, context?: HttpContext): Observable<StrictHttpResponse<KeywordListResponse>> {
  const rb = new RequestBuilder(rootUrl, getKeywordsListKeywordsListGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<KeywordListResponse>;
    })
  );
}

getKeywordsListKeywordsListGet.PATH = '/keywords/list';
