/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DownloadAssetChallengesIdAssetsFileNameGet$Params {
  id: string;
  file_name: string;
}

export function downloadAssetChallengesIdAssetsFileNameGet(http: HttpClient, rootUrl: string, params: DownloadAssetChallengesIdAssetsFileNameGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, downloadAssetChallengesIdAssetsFileNameGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('file_name', params.file_name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

downloadAssetChallengesIdAssetsFileNameGet.PATH = '/challenges/{id}/assets/{file_name}';
