/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ManuallyStartResponse } from '../../models/manually-start-response';

export interface AdminUpdateChallengesAdminUpdateChallengesPost$Params {
  'x-api-key': string;
}

export function adminUpdateChallengesAdminUpdateChallengesPost(http: HttpClient, rootUrl: string, params: AdminUpdateChallengesAdminUpdateChallengesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ManuallyStartResponse>> {
  const rb = new RequestBuilder(rootUrl, adminUpdateChallengesAdminUpdateChallengesPost.PATH, 'post');
  if (params) {
    rb.header('x-api-key', params['x-api-key'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ManuallyStartResponse>;
    })
  );
}

adminUpdateChallengesAdminUpdateChallengesPost.PATH = '/admin/update-challenges';
