/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DatabasecheckResponse } from '../../models/databasecheck-response';

export interface DatabasecheckDatabasecheckGet$Params {
}

export function databasecheckDatabasecheckGet(http: HttpClient, rootUrl: string, params?: DatabasecheckDatabasecheckGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DatabasecheckResponse>> {
  const rb = new RequestBuilder(rootUrl, databasecheckDatabasecheckGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DatabasecheckResponse>;
    })
  );
}

databasecheckDatabasecheckGet.PATH = '/databasecheck';
