/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DataApiStatusResponse } from '../../models/data-api-status-response';

export interface GetDataApiStatusAdminDataApiStatusGet$Params {
  'x-api-key': string;
}

export function getDataApiStatusAdminDataApiStatusGet(http: HttpClient, rootUrl: string, params: GetDataApiStatusAdminDataApiStatusGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DataApiStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, getDataApiStatusAdminDataApiStatusGet.PATH, 'get');
  if (params) {
    rb.header('x-api-key', params['x-api-key'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DataApiStatusResponse>;
    })
  );
}

getDataApiStatusAdminDataApiStatusGet.PATH = '/admin/data-api-status';
