/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ScheduleResponse } from '../../models/schedule-response';

export interface GetScheduleAdminScheduleGet$Params {
  'x-api-key': string;
}

export function getScheduleAdminScheduleGet(http: HttpClient, rootUrl: string, params: GetScheduleAdminScheduleGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ScheduleResponse>> {
  const rb = new RequestBuilder(rootUrl, getScheduleAdminScheduleGet.PATH, 'get');
  if (params) {
    rb.header('x-api-key', params['x-api-key'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ScheduleResponse>;
    })
  );
}

getScheduleAdminScheduleGet.PATH = '/admin/schedule';
