/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ScheduleRequest } from '../../models/schedule-request';
import { ScheduleUpdateResponse } from '../../models/schedule-update-response';

export interface UpdateScheduleAdminSchedulePut$Params {
  'x-api-key': string;
      body: ScheduleRequest
}

export function updateScheduleAdminSchedulePut(http: HttpClient, rootUrl: string, params: UpdateScheduleAdminSchedulePut$Params, context?: HttpContext): Observable<StrictHttpResponse<ScheduleUpdateResponse>> {
  const rb = new RequestBuilder(rootUrl, updateScheduleAdminSchedulePut.PATH, 'put');
  if (params) {
    rb.header('x-api-key', params['x-api-key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ScheduleUpdateResponse>;
    })
  );
}

updateScheduleAdminSchedulePut.PATH = '/admin/schedule';
