/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubgraphListResponse } from '../../models/subgraph-list-response';

export interface GetSublistSublistGet$Params {
  start: string;
  end: string;
}

export function getSublistSublistGet(http: HttpClient, rootUrl: string, params: GetSublistSublistGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubgraphListResponse>>> {
  const rb = new RequestBuilder(rootUrl, getSublistSublistGet.PATH, 'get');
  if (params) {
    rb.query('start', params.start, {});
    rb.query('end', params.end, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SubgraphListResponse>>;
    })
  );
}

getSublistSublistGet.PATH = '/sublist';
