/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssetResponse {
  file_name: string;
  file_size: number;
  id: number;
  mime_type: (string | null);
  relative_path: string;
}
