/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssetResponse } from '../models/asset-response';
export interface ChallengeContentResponse {
  assets: Array<AssetResponse>;
  content_markdown: string;
  id: string;
  imported_at: string;
  source_commit: (string | null);
}
