/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChallengeByKeywordListItem } from '../models/challenge-by-keyword-list-item';
export interface ChallengesByKeywordListResponse {
  items?: Array<ChallengeByKeywordListItem>;
}
