/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChallengeEdge } from '../models/challenge-edge';
import { ChallengeNode } from '../models/challenge-node';
export interface ChallengesByKeywordGraphResponse {
  edges?: Array<ChallengeEdge>;
  nodes?: Array<ChallengeNode>;
}
