/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChallengeListResponse {
  author?: (Array<string> | string | null);
  firstused?: (string | null);
  id: string;
  keywords?: Array<string>;
  teaches?: (string | null);
}
