/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GraphEdgeResponse } from '../models/graph-edge-response';
import { GraphNodeResponse } from '../models/graph-node-response';
export interface DependencyGraphResponse {
  edges?: Array<GraphEdgeResponse>;
  nodes?: Array<GraphNodeResponse>;
}
