/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Edge } from '../models/edge';
import { Node } from '../models/node';
export interface GraphResponse {
  edges: Array<Edge>;
  nodes: Array<Node>;
}
