/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KeywordEdge } from '../models/keyword-edge';
import { KeywordNode } from '../models/keyword-node';
export interface KeywordGraphResponse {
  edges?: Array<KeywordEdge>;
  nodes?: Array<KeywordNode>;
}
