/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NeighborChallenge } from '../models/neighbor-challenge';
export interface NeighborsResponse {
  next?: Array<NeighborChallenge>;
  previous?: Array<NeighborChallenge>;
}
