/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScheduleResponse } from '../models/schedule-response';
export interface ScheduleUpdateResponse {
  message: string;
  schedule: ScheduleResponse;
  status: string;
}
