/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GraphEdge } from '../models/graph-edge';
import { GraphNode } from '../models/graph-node';
export interface SubgraphGraphResponse {
  edges?: Array<GraphEdge>;
  nodes?: Array<GraphNode>;
}
