/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateStatusResponse {
  export_stats?: ({
[key: string]: any;
} | null);
  fetch_stats?: ({
[key: string]: any;
} | null);
  message?: (string | null);
  status: string;
}
