/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NeighborsResponse } from '../../models/neighbors-response';

export interface GetChallengeNeighborsChallengesNeighborsGet$Params {
  id: string;
}

export function getChallengeNeighborsChallengesNeighborsGet(http: HttpClient, rootUrl: string, params: GetChallengeNeighborsChallengesNeighborsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<NeighborsResponse>> {
  const rb = new RequestBuilder(rootUrl, getChallengeNeighborsChallengesNeighborsGet.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NeighborsResponse>;
    })
  );
}

getChallengeNeighborsChallengesNeighborsGet.PATH = '/challenges/neighbors';
