/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DependencyGraphResponse } from '../../models/dependency-graph-response';

export interface GetGraphDependenciesGraphChallengesDependsOnGet$Params {
  id: string;
}

export function getGraphDependenciesGraphChallengesDependsOnGet(http: HttpClient, rootUrl: string, params: GetGraphDependenciesGraphChallengesDependsOnGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DependencyGraphResponse>> {
  const rb = new RequestBuilder(rootUrl, getGraphDependenciesGraphChallengesDependsOnGet.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DependencyGraphResponse>;
    })
  );
}

getGraphDependenciesGraphChallengesDependsOnGet.PATH = '/graph/challenges/depends-on';
