/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GraphResponse } from '../../models/graph-response';

export interface GetGraphGraphGet$Params {
}

export function getGraphGraphGet(http: HttpClient, rootUrl: string, params?: GetGraphGraphGet$Params, context?: HttpContext): Observable<StrictHttpResponse<GraphResponse>> {
  const rb = new RequestBuilder(rootUrl, getGraphGraphGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GraphResponse>;
    })
  );
}

getGraphGraphGet.PATH = '/graph';
